/*
 * GeoDialog.java
 *
 * Created on 24 de abril de 2009, 6:28
 */

package simuldp;
import org.jdesktop.application.Action;
import simulacion.ControlSim;
import javax.swing.*;
/**
 *
 * @author  bruno
 */
public class GeoDialog extends javax.swing.JDialog {

    /** Creates new form GeoDialog */
    public GeoDialog(java.awt.Frame parent, boolean modal, ControlSim control, SimulDPView aThis) {
        super(parent, modal);
        this.control=control;
        this.SimulDPView=aThis;
        initComponents();
    }

    
    @Action public void cierreDia() {
        setVisible(false);        
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jLabel4 = new javax.swing.JLabel();
      jScrollPane2 = new javax.swing.JScrollPane();
      jTextPane1 = new javax.swing.JTextPane();
      jPanel3 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      ProbFrac = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      NumObs = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(simuldp.SimulDPApp.class).getContext().getResourceMap(GeoDialog.class);
      setTitle(resourceMap.getString("Form.title")); // NOI18N
      setName("Form"); // NOI18N
      setResizable(false);

      jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
      jPanel1.setName("jPanel1"); // NOI18N

      jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
      jButton1.setName("jButton1"); // NOI18N
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
      jButton2.setName("jButton2"); // NOI18N
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });

      jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
      jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
      jLabel4.setName("jLabel4"); // NOI18N

      jScrollPane2.setName("jScrollPane2"); // NOI18N

      jTextPane1.setEditable(false);
      jTextPane1.setText(resourceMap.getString("jTextPane1.text")); // NOI18N
      jTextPane1.setName("jTextPane1"); // NOI18N
      jScrollPane2.setViewportView(jTextPane1);

      jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel3.border.title"))); // NOI18N
      jPanel3.setName("jPanel3"); // NOI18N

      jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
      jLabel2.setName("jLabel2"); // NOI18N

      ProbFrac.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      ProbFrac.setText(resourceMap.getString("ProbFrac.text")); // NOI18N
      ProbFrac.setName("ProbFrac"); // NOI18N

      jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
      jLabel3.setName("jLabel3"); // NOI18N

      NumObs.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      NumObs.setText(resourceMap.getString("NumObs.text")); // NOI18N
      NumObs.setName("NumObs"); // NOI18N

      org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(jPanel3Layout.createSequentialGroup()
                  .add(jLabel2)
                  .add(78, 78, 78)
                  .add(ProbFrac, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
               .add(jPanel3Layout.createSequentialGroup()
                  .add(jLabel3)
                  .add(69, 69, 69)
                  .add(NumObs, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
            .addContainerGap())
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(jLabel2)
               .add(ProbFrac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
               .add(jLabel3)
               .add(NumObs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(22, Short.MAX_VALUE))
      );

      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
      jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
      jLabel1.setName("jLabel1"); // NOI18N
      jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

      org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
               .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
               .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4)
               .add(jPanel1Layout.createSequentialGroup()
                  .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                     .add(jPanel1Layout.createSequentialGroup()
                        .add(72, 72, 72)
                        .add(jButton1)
                        .add(18, 18, 18)
                        .add(jButton2))
                     .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                  .add(47, 47, 47)
                  .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 296, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                  .add(26, 26, 26)))
            .add(24, 24, 24))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .add(jLabel4)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
               .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                  .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                  .add(28, 28, 28)
                  .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                     .add(jButton1)
                     .add(jButton2)))
               .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 196, Short.MAX_VALUE))
            .addContainerGap())
      );

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   String Error;
   Validaciones DatoValido= new Validaciones();
if(!DatoValido.EntreCeroyUno(ProbFrac.getText())){
      Error="El valor de la probabilidad es incorrecto\n debe estar entre el rango de 0 y 1";
      JOptionPane.showMessageDialog(null,Error, "ERROR",JOptionPane.ERROR_MESSAGE);}
else
{
 if((!DatoValido.EsEntero(NumObs.getText())))
 {
     Error="Numero de Observaciones es Incorrecto";
      JOptionPane.showMessageDialog(null,Error, "ERROR",JOptionPane.ERROR_MESSAGE);
 }
 else
 {
   Double ProbEx=new Double(this.ProbFrac.getText());
   Double NumOb=new Double(this.NumObs.getText());
   this.control.CrearObs(1, NumOb.intValue());
   control.GetObs().GenObsDisc(ProbEx.doubleValue(), 0);
   control.GetObs().ObsMaxMin();
   JFrame mainFrame = SimulDPApp.getApplication().getMainFrame();
   ResDialog = new ResDialog(mainFrame, false, control, "Observaciones Aleatorias - Distribución Geometrica", 1, this.SimulDPView);
   ResDialog.setLocationRelativeTo(mainFrame);
   SimulDPApp.getApplication().show(ResDialog);
 }
}

}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.cierreDia();
}//GEN-LAST:event_jButton2ActionPerformed

    
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextField NumObs;
   private javax.swing.JTextField ProbFrac;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JTextPane jTextPane1;
   // End of variables declaration//GEN-END:variables
   private ControlSim control;
   private ResDialog ResDialog;
   private SimulDPView SimulDPView;
}
